### ISSUE TITLE
Viewer performance regressions

### ISSUE THREAD

**Issue by avirshup** [Autodesk/notebook-molecular-visualization#24]
Seeing some viewer slowdowns in the new version, especially for larger structures. Will run a profiler on the Python side soon to see if there's an obvious culprit. Here are the serious issues:
1. Drawing large structures freezes the browser for as long as 30 seconds before loading (using chrome at least) - the old version renders in about 2-3 seconds:

```
m = mdt.from_pdb('1kbu')
mol = mdt.build_assembly(m, 1)
viewer = mol.draw(display=True)
```
1. In the above structure, clicking on an atom makes my browser freeze for about 10 seconds before the selection is rendered and the text box appears (<<1 second before merge):

![image](https://zube.io/files/Autodesk/0166a31cd26a61868d9487d0da44a81a.png)
1. Trajectory animations take a really long time to appear - and can actually crash the browser. This one (following on the previous example) freezes for about 3 minutes, then crashes my browser:

```
rotation = mdt.Trajectory(mol)
rotation.new_frame()
for i in xrange(20):
    mol.rotate(20.0 * u.degrees, [1,0,0])
    rotation.new_frame()
rotation.draw()
```
1. Trajectory animations take a really long time to appear. They also appear to lag behind the slider by a few seconds. Following on the previous example:

```
mol = mdt.build_dna_helix('ACTGCGTA')
rotation = mdt.Trajectory(mol)
rotation.new_frame()
for i in xrange(20):
    mol.rotate(20.0 * u.degrees, [1,0,0])
    rotation.new_frame()
rotation.draw()
```

![rotationslow.gif](https://zube.io/files/Autodesk/24adf697c0a0cd45fb583b50f38ca5c4.gif)

Previous behavior: Viewer appears in 3-4 seconds. There's actually still a UI lag, but not as bad, even for larger molecules:
![rotation.gif](https://zube.io/files/Autodesk/80e1b6462bd3f3a80ee0a33d4d6ba227.gif)

**Comment by justinmc** [comment]
@avirshup I think I improved everything mentioned, should be at least as fast as before now...  Can you try it out and let me know what you think when you get a chance?  Two PRs:

https://github.com/Autodesk/molecule-3d-for-react/pull/9
https://github.com/Autodesk/notebook-molecular-visualization/pull/27

**Comment by avirshup** [comment]
For my later reference:

I tried this, and initially couldn't get it to work, mostly because I wasn't smart enough to pull the companion PRs from the javascript libraries :(

With @justinmc's help, here's a record of how to test these PRs:

```
git clone https://github.com/Autodesk/molecule-3d-for-react
cd /path/to/molecule-3d-for-react
git fetch
git checkout large-molecule-perf
git pull origin large-molecule-perf
npm install
npm run build
npm link
cd /path/to/notebook-molecular-visualization/js
npm link molecule-3d-for-react
cd ../
python setup.py jsdeps
```

Next, make sure that Jupyter is loading THIS version of the `nbmolviz-js`. It might be stored i one of several places. You can remove ALL old versions with:

```
jupyter nbextension uninstall --python nbmolviz
jupyter nbextension uninstall --python --sys-prefix nbmolviz
jupyter nbextension uninstall --python --system nbmolviz
```

And then install the new one with `jupyter nbextension install --python --sys-prefix nbmolviz`.

(`--sys-prefix` is probably the best installation location because it works with isolated environments)

**Comment by justinmc** [comment]
Fixed with: https://github.com/Autodesk/notebook-molecular-visualization/pull/27
