### ISSUE TITLE
Labels don't disappear when "label atoms" checkbox is deselected in GeometryBuilder widget

### ISSUE THREAD

**Issue by avirshup** [Autodesk/notebook-molecular-visualization#40]
This is probably a simple one:

```python
mol = mdt.from_smiles('C=C')
mdt.widgets.GeometryBuilder(mol)
```

Then click the checkbox next to "label atoms" a few times:

![atom_labels_stay](https://cloud.githubusercontent.com/assets/9388007/19951153/54ae4506-a119-11e6-9df8-0ec24c7b6297.gif)

**Comment by justinmc** [comment]
PR here: https://github.com/Autodesk/molecule-3d-for-react/pull/16

**Comment by justinmc** [comment]
PR merged and new version released: https://github.com/Autodesk/molecule-3d-for-react/releases/tag/v0.2.4
